# Generated by Django 2.1.4 on 2018-12-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20181212_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='job',
            name='functionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.Functionary', verbose_name='Funcionário'),
        ),
    ]
