# Generated by Django 2.1.4 on 2018-12-13 13:45

import dashboard.job.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20181212_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=dashboard.job.models.get_job_image_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem do Trabalho',
                'verbose_name_plural': 'Imagens do Trabalho',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='accepted',
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='job',
            name='functionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.Functionary', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='job.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='job.Job', verbose_name='Trabalho'),
        ),
    ]
