# Generated by Django 2.1.4 on 2018-12-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_finish_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='finish_datetime',
            new_name='end_datetime',
        ),
        migrations.AddField(
            model_name='job',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Inicio'),
        ),
    ]
