# Generated by Django 2.1.4 on 2018-12-12 20:44

import dashboard.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181212_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.account.models.get_user_image_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.account.models.get_user_image_path, verbose_name='Imagem'),
        ),
    ]
