# Generated by Django 2.1.4 on 2018-12-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181212_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
